package com.nongcang.server.common.exception;

import org.springframework.http.HttpStatus;

public enum CommonErrorCode implements ErrorCode {

	OK("OK", "操作成功", HttpStatus.OK),
	BAD_REQUEST("BAD_REQUEST", "请求参数格式错误", HttpStatus.BAD_REQUEST),
	VALIDATION_FAILED("VALIDATION_FAILED", "请求参数校验失败", HttpStatus.UNPROCESSABLE_ENTITY),
	UNAUTHORIZED("UNAUTHORIZED", "登录已失效，请重新登录", HttpStatus.UNAUTHORIZED),
	FORBIDDEN("FORBIDDEN", "当前账号无权执行该操作", HttpStatus.FORBIDDEN),
	INVALID_CREDENTIALS("INVALID_CREDENTIALS", "账号或密码错误", HttpStatus.UNAUTHORIZED),
	INVALID_ACCESS_TOKEN("INVALID_ACCESS_TOKEN", "访问令牌无效，请重新登录", HttpStatus.UNAUTHORIZED),
	INVALID_REFRESH_TOKEN("INVALID_REFRESH_TOKEN", "刷新令牌无效，请重新登录", HttpStatus.UNAUTHORIZED),
	RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND", "请求的资源不存在", HttpStatus.NOT_FOUND),
	CATEGORY_NOT_FOUND("CATEGORY_NOT_FOUND", "产品分类不存在", HttpStatus.NOT_FOUND),
	CATEGORY_CODE_DUPLICATED("CATEGORY_CODE_DUPLICATED", "分类编号已存在", HttpStatus.CONFLICT),
	CATEGORY_NAME_DUPLICATED("CATEGORY_NAME_DUPLICATED", "同级分类名称重复", HttpStatus.CONFLICT),
	CATEGORY_PARENT_NOT_FOUND("CATEGORY_PARENT_NOT_FOUND", "上级分类不存在", HttpStatus.BAD_REQUEST),
	CATEGORY_PARENT_INVALID("CATEGORY_PARENT_INVALID", "不能将当前分类挂到自己或自己的下级分类下", HttpStatus.CONFLICT),
	CATEGORY_LEVEL_EXCEEDED("CATEGORY_LEVEL_EXCEEDED", "分类层级超过当前系统限制", HttpStatus.CONFLICT),
	CATEGORY_HAS_CHILDREN("CATEGORY_HAS_CHILDREN", "当前分类下存在子分类，不能删除", HttpStatus.CONFLICT),
	PRODUCT_UNIT_NOT_FOUND("PRODUCT_UNIT_NOT_FOUND", "产品单位不存在", HttpStatus.NOT_FOUND),
	PRODUCT_UNIT_CODE_DUPLICATED("PRODUCT_UNIT_CODE_DUPLICATED", "产品单位编号已存在", HttpStatus.CONFLICT),
	PRODUCT_UNIT_NAME_DUPLICATED("PRODUCT_UNIT_NAME_DUPLICATED", "产品单位名称已存在", HttpStatus.CONFLICT),
	PRODUCT_UNIT_IN_USE("PRODUCT_UNIT_IN_USE", "产品单位已被产品档案引用，不能删除", HttpStatus.CONFLICT),
	PRODUCT_ORIGIN_NOT_FOUND("PRODUCT_ORIGIN_NOT_FOUND", "产地信息不存在", HttpStatus.NOT_FOUND),
	PRODUCT_ORIGIN_CODE_DUPLICATED("PRODUCT_ORIGIN_CODE_DUPLICATED", "产地编号已存在", HttpStatus.CONFLICT),
	PRODUCT_ORIGIN_NAME_DUPLICATED("PRODUCT_ORIGIN_NAME_DUPLICATED", "产地名称已存在", HttpStatus.CONFLICT),
	PRODUCT_ORIGIN_IN_USE("PRODUCT_ORIGIN_IN_USE", "产地已被产品档案引用，不能删除", HttpStatus.CONFLICT),
	STORAGE_CONDITION_NOT_FOUND("STORAGE_CONDITION_NOT_FOUND", "储存条件不存在", HttpStatus.NOT_FOUND),
	STORAGE_CONDITION_IN_USE("STORAGE_CONDITION_IN_USE", "储存条件已被产品分类引用，不能删除", HttpStatus.CONFLICT),
	STORAGE_CONDITION_CODE_DUPLICATED("STORAGE_CONDITION_CODE_DUPLICATED", "储存条件编号已存在", HttpStatus.CONFLICT),
	STORAGE_CONDITION_NAME_DUPLICATED("STORAGE_CONDITION_NAME_DUPLICATED", "储存条件名称已存在", HttpStatus.CONFLICT),
	STORAGE_CONDITION_LIGHT_REQUIREMENT_INVALID("STORAGE_CONDITION_LIGHT_REQUIREMENT_INVALID", "避光要求不在允许范围内", HttpStatus.CONFLICT),
	STORAGE_CONDITION_VENTILATION_REQUIREMENT_INVALID("STORAGE_CONDITION_VENTILATION_REQUIREMENT_INVALID", "通风要求不在允许范围内", HttpStatus.CONFLICT),
	STORAGE_CONDITION_TEMPERATURE_RANGE_INVALID("STORAGE_CONDITION_TEMPERATURE_RANGE_INVALID", "温度范围配置不正确", HttpStatus.CONFLICT),
	STORAGE_CONDITION_HUMIDITY_RANGE_INVALID("STORAGE_CONDITION_HUMIDITY_RANGE_INVALID", "湿度范围配置不正确", HttpStatus.CONFLICT),
	BUSINESS_RULE_VIOLATION("BUSINESS_RULE_VIOLATION", "业务处理失败", HttpStatus.CONFLICT),
	DEMO_BUSINESS_ERROR("DEMO_BUSINESS_ERROR", "这是一个演示业务错误", HttpStatus.CONFLICT),
	INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR", "系统繁忙，请稍后再试", HttpStatus.INTERNAL_SERVER_ERROR),
	SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE", "服务暂时不可用，请稍后再试", HttpStatus.SERVICE_UNAVAILABLE);

	private final String code;

	private final String message;

	private final HttpStatus status;

	CommonErrorCode(String code, String message, HttpStatus status) {
		this.code = code;
		this.message = message;
		this.status = status;
	}

	@Override
	public String code() {
		return code;
	}

	@Override
	public String message() {
		return message;
	}

	@Override
	public HttpStatus status() {
		return status;
	}
}
