spring.application.name=server
logging.pattern.level=%5p [traceId=%X{traceId:-}]
spring.mvc.throw-exception-if-no-handler-found=true
spring.datasource.url=jdbc:mysql://127.0.0.1:2017/nong-cang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=200517ZXfWJl
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=10000
