USE `nong-cang`;

CREATE TABLE IF NOT EXISTS `quality_inspection` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '质检单ID',
  `inspection_code` VARCHAR(64) NOT NULL COMMENT '质检单编号',
  `source_type` VARCHAR(32) NOT NULL COMMENT '来源类型：INBOUND_RECORD/INVENTORY_STOCK',
  `source_id` BIGINT NOT NULL COMMENT '来源ID',
  `source_code` VARCHAR(64) NOT NULL COMMENT '来源编号',
  `source_label` VARCHAR(255) NOT NULL COMMENT '来源展示文本',
  `product_id` BIGINT NOT NULL COMMENT '产品ID',
  `warehouse_id` BIGINT NOT NULL COMMENT '仓库ID',
  `zone_id` BIGINT NOT NULL COMMENT '库区ID',
  `location_id` BIGINT NOT NULL COMMENT '库位ID',
  `inspect_quantity` DECIMAL(14,3) NOT NULL COMMENT '送检数量',
  `qualified_quantity` DECIMAL(14,3) NOT NULL COMMENT '合格数量',
  `unqualified_quantity` DECIMAL(14,3) NOT NULL COMMENT '不合格数量',
  `result_status` TINYINT NOT NULL COMMENT '结果：1合格 2部分不合格 3不合格',
  `remarks` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quality_inspection_code` (`inspection_code`),
  KEY `idx_quality_inspection_source` (`source_type`, `source_id`),
  KEY `idx_quality_inspection_product` (`product_id`),
  KEY `idx_quality_inspection_warehouse` (`warehouse_id`),
  CONSTRAINT `fk_quality_inspection_product` FOREIGN KEY (`product_id`) REFERENCES `product_archive` (`id`),
  CONSTRAINT `fk_quality_inspection_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouse` (`id`),
  CONSTRAINT `fk_quality_inspection_zone` FOREIGN KEY (`zone_id`) REFERENCES `warehouse_zone` (`id`),
  CONSTRAINT `fk_quality_inspection_location` FOREIGN KEY (`location_id`) REFERENCES `warehouse_location` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='质检单表';

CREATE TABLE IF NOT EXISTS `abnormal_stock` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '异常库存ID',
  `abnormal_code` VARCHAR(64) NOT NULL COMMENT '异常库存编号',
  `quality_inspection_id` BIGINT NOT NULL COMMENT '来源质检单ID',
  `inspection_code` VARCHAR(64) NOT NULL COMMENT '来源质检单编号',
  `product_id` BIGINT NOT NULL COMMENT '产品ID',
  `warehouse_id` BIGINT NOT NULL COMMENT '仓库ID',
  `zone_id` BIGINT NOT NULL COMMENT '库区ID',
  `location_id` BIGINT NOT NULL COMMENT '库位ID',
  `locked_quantity` DECIMAL(14,3) NOT NULL COMMENT '锁定数量',
  `status` TINYINT NOT NULL COMMENT '状态：1锁定中 2已释放 3已转损耗',
  `reason` VARCHAR(64) NOT NULL COMMENT '异常原因',
  `remarks` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `processed_at` DATETIME DEFAULT NULL COMMENT '处理时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_abnormal_stock_code` (`abnormal_code`),
  UNIQUE KEY `uk_abnormal_stock_inspection` (`quality_inspection_id`),
  KEY `idx_abnormal_stock_product` (`product_id`),
  KEY `idx_abnormal_stock_warehouse` (`warehouse_id`),
  CONSTRAINT `fk_abnormal_stock_quality_inspection` FOREIGN KEY (`quality_inspection_id`) REFERENCES `quality_inspection` (`id`),
  CONSTRAINT `fk_abnormal_stock_product` FOREIGN KEY (`product_id`) REFERENCES `product_archive` (`id`),
  CONSTRAINT `fk_abnormal_stock_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouse` (`id`),
  CONSTRAINT `fk_abnormal_stock_zone` FOREIGN KEY (`zone_id`) REFERENCES `warehouse_zone` (`id`),
  CONSTRAINT `fk_abnormal_stock_location` FOREIGN KEY (`location_id`) REFERENCES `warehouse_location` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='异常锁定库存表';
